[package]
name = "rev-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lexpr = "0.2.7"
rand = "0.8.5"

[patch.crates-io]
lexpr = { path = "lexpr-rs/lexpr" }